ALTER TABLE "canon_documents" ADD CONSTRAINT "canon_documents_sensitivity_check" CHECK ("canon_documents"."sensitivity" in ('PUBLIC', 'INTERNAL', 'PRIVATE', 'SENSITIVE', 'HIGHLY_SENSITIVE'));--> statement-breakpoint
ALTER TABLE "canon_sections" ADD CONSTRAINT "canon_sections_governance_check" CHECK ("canon_sections"."information_state" = 'CANONICAL' and "canon_sections"."trust_class" = 'SYSTEM_CONSTITUTIONAL_INSTRUCTION' and "canon_sections"."authority_class" = 'PROTECTED_CONSTITUTION');--> statement-breakpoint
ALTER TABLE "canon_sections" ADD CONSTRAINT "canon_sections_sensitivity_check" CHECK ("canon_sections"."sensitivity" in ('PUBLIC', 'INTERNAL', 'PRIVATE', 'SENSITIVE', 'HIGHLY_SENSITIVE'));--> statement-breakpoint
ALTER TABLE "canon_sections" ADD CONSTRAINT "canon_sections_token_estimate_check" CHECK ("canon_sections"."token_estimate" > 0);--> statement-breakpoint
ALTER TABLE "context_trace_items" ADD CONSTRAINT "context_trace_items_sensitivity_check" CHECK ("context_trace_items"."sensitivity" in ('PUBLIC', 'INTERNAL', 'PRIVATE', 'SENSITIVE', 'HIGHLY_SENSITIVE'));--> statement-breakpoint
ALTER TABLE "context_trace_items" ADD CONSTRAINT "context_trace_items_token_estimate_check" CHECK ("context_trace_items"."token_estimate" >= 0);--> statement-breakpoint
ALTER TABLE "knowledge_records" ADD CONSTRAINT "knowledge_records_information_state_check" CHECK ("knowledge_records"."information_state" in ('CURRENT_FACT', 'HISTORICAL_FACT', 'DECISION', 'PREFERENCE', 'PROPOSAL', 'HYPOTHESIS', 'BRAINSTORM', 'SUPERSEDED', 'DISPUTED', 'UNKNOWN'));--> statement-breakpoint
ALTER TABLE "knowledge_records" ADD CONSTRAINT "knowledge_records_trust_class_check" CHECK ("knowledge_records"."trust_class" in ('AUTHORIZED_FOUNDER_INSTRUCTION', 'AUTHORIZED_OPERATIONAL_POLICY', 'TRUSTED_FACT_SOURCE', 'UNTRUSTED_CONTENT'));--> statement-breakpoint
ALTER TABLE "knowledge_records" ADD CONSTRAINT "knowledge_records_authority_class_check" CHECK ("knowledge_records"."authority_class" in ('CURRENT_FOUNDER_DIRECTION', 'CURRENT_VERIFIED_STATE', 'EXPLICIT_DECISION', 'DOMAIN_CANON', 'VALIDATED_KNOWLEDGE', 'PREFERENCE', 'INFERENCE', 'UNTRUSTED_CONTENT'));--> statement-breakpoint
ALTER TABLE "knowledge_records" ADD CONSTRAINT "knowledge_records_sensitivity_check" CHECK ("knowledge_records"."sensitivity" in ('PUBLIC', 'INTERNAL', 'PRIVATE', 'SENSITIVE', 'HIGHLY_SENSITIVE'));--> statement-breakpoint
ALTER TABLE "knowledge_records" ADD CONSTRAINT "knowledge_records_confidence_check" CHECK ("knowledge_records"."confidence" is null or ("knowledge_records"."confidence" >= 0 and "knowledge_records"."confidence" <= 100));